version: '3.8'

services:
  gau-account-service:
    image: iamqbao/gau_account_service:latest
    container_name: gau-account-service
    environment:
      - PGPOOL_URL=${PGPOOL_URL}
    restart: always
    volumes:
      - .env:/gau_account/.env
    networks:
      - app-network

  gau-account-service-backup:
    image: iamqbao/gau_account_service:latest
    container_name: gau-account-service-backup
    environment:
      - PGPOOL_URL=${PGPOOL_URL}
    restart: always
    volumes:
      - .env:/gau_account/.env
    networks:
      - app-network

  #  gau-validation-service:
  #    image: iamqbao/gau_validation_service:latest
  #    container_name: gau-validation-service
  #    restart: always
  #    volumes:
  #      - .env:/gau_validation/.env
  #    networks:
  #      - app-network
  #
  #  gau-validation-service-backup:
  #    image: iamqbao/gau_validation_service:latest
  #    container_name: gau-validation-service-backup
  #    restart: always
  #    volumes:
  #      - .env:/gau_validation/.env
  #    networks:
  #      - app-network
  gau-cdn-service:
    image: iamqbao/gau_cdn_service:latest
    container_name: gau-cdn-service
    restart: always
    volumes:
      - ./cdn.env:/gau_cdn/cdn.env
    networks:
      - app-network


networks:
  app-network:
    external: true
