version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: unless-stopped
    expose:
      - "15672"
      - "5672"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.sh:ro
    command: [ "/bin/sh", "/docker-entrypoint.sh" ]
    networks:
      - app-network
  

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    restart: unless-stopped
    ports:
      - "7700"
    env_file:
      - meili.env
    volumes:
      - ./meili_data:/meili_data
    networks:
      - app-network


networks:
  app-network:
    external: true
