version: '3.8'

services:
  gau-phim-backend:
    image: iamqbao/gau_phim_backend:latest
    container_name: gau-phim-backend
    restart: always
    volumes:
      - .env.flix:/gau_phim/.env.flix
    networks:
      - app-network

  gau-phim-backend-backup:
    image: iamqbao/gau_phim_backend:latest
    container_name: gau-phim-backend-backup
    restart: always
    volumes:
      - .env.flix:/gau_phim/.env.flix
    networks:
      - app-network

  gau-phim-frontend:
    image: iamqbao/gau_phim_frontend:latest
    container_name: gau-phim-frontend
    restart: always
    volumes:
      - .env:/app/.env
    networks:
      - app-network

networks:
  app-network:
    external: true
