version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - .env
    networks:
      - app-network
    command: sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    volumes:
      - redis-data:/data

networks:
  app-network:
    name: app-network
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/24"
    external: true

volumes:
  postgres-data:
  redis-data:
