apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./base/deployment.yaml
  - ./base/service.yaml
  - ./base/ingress.yaml
  - ./base/hpa.yaml
  - ./base/configmap.yaml
  - ./base/namespace.yaml